### ISSUE TITLE
Implement Action Point counter for each submitted choice

### ISSUE THREAD

**Issue by sushins94** [jtruong04/SchrodingerCheckers#20]
-1 entangle
-1 flip
-2 disentangle
0 skip => End turn

**Comment by sushins94** [comment]
As paort of this we need to also kep track of whose turn it is.

**Comment by MSchiavi** [comment]
We keep track of who's turn it is when we initialize the lobby. For now, I would just make it so that you can "play" the game as two people from one person's PoV if that makes sense.
