### ISSUE TITLE
Graphic Problem on current player's side

### ISSUE THREAD

**Issue by MSchiavi** [jtruong04/SchrodingerCheckers#27]
On the current player's side, when they destroy a tunnel and then re place a tunnel, the tunnel image does not update according to the bitstate as they cycle through. 

The bitstate is changing properly, because the image cycles the right way on the other players side, once the turn ends the image updates accordingly on the current players side.

**Comment by sushins94** [comment]
Bug is because of the if conditions for this.setstate in TunnelChange. Before fixing this however we may need to get a proper flow of turns and submits implemented.
