### ISSUE TITLE
Demo page on server

### ISSUE THREAD

**Issue by mjpmorse** [jtruong04/SchrodingerCheckers#6]

**Comment by jtruong04** [comment]
This right now works kinda. Link to it is in the Google doc. Some manual labor required. Right now, just push to test-build and tell me to pull from there. Once automatic process is done, I'll close this.

**Comment by MSchiavi** [comment]
Do you intend for the test_build branch to be the staging branch before we push things to master?

**Comment by jtruong04** [comment]
Sure

**Comment by MSchiavi** [comment]
word once you figure out the automatic pushing we can do that. Our workflow will change a little, ill write something up in the doc later.
